# Generated by Django 4.2.5 on 2023-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_protfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='protfolio',
            name='image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
