# Generated by Django 4.2.5 on 2023-12-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_id_cart_product_alter_cart_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
