# Generated by Django 4.2.5 on 2023-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_cart_phone_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
